In [1]:
# Load main packages
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt # plotting handling
import seaborn as sns # plotting handling
import altair as alt # plotting handling
import time # timer

In [2]:
# Load 
data = pd.read_csv('C:/Users/micha/OneDrive/Documents/repos/Soto Instagram test/Instagram_Data.csv')

In [3]:
# Clean/Preprocessing
data['Date Posted'] = pd.to_datetime(data['Date Posted']) # Convert to datetime
data['Type'] = data['Type'].astype('category') # Change to category
data['Day Name'] = data['Date Posted'].dt.strftime("%A") # Get day name
data['Workday'] = data['Day Name'].apply(lambda x: False if x in ['Saturday', 'Sunday'] else True) # Is workday or not

In [4]:
data.head(40)

,User ID,Likes,Days passed from post,Likes Score,Type,Number of Tags,Number of Comments,Date Posted,Year,Month,Day,Hour,Minute,Day Name,Workday
0,1,506,657,0.74,Image,3,11,2019-05-12 21:18:00,2019,5,12,21,18,Sunday,False
1,1,385,657,0.57,Image,0,1,2019-05-12 14:25:00,2019,5,12,14,25,Sunday,False
2,1,373,666,0.55,Images,4,15,2019-05-03 15:18:00,2019,5,3,15,18,Friday,True
3,1,312,667,0.46,Images,4,1,2019-05-02 16:40:00,2019,5,2,16,40,Thursday,True
4,1,513,674,0.75,Images,5,0,2019-04-25 16:51:00,2019,4,25,16,51,Thursday,True
5,1,539,677,0.79,Images,3,3,2019-04-22 20:03:00,2019,4,22,20,3,Monday,True
6,1,330,677,0.49,Image,0,3,2019-04-22 15:07:00,2019,4,22,15,7,Monday,True
7,1,472,681,0.69,Images,3,7,2019-04-18 14:44:00,2019,4,18,14,44,Thursday,True
8,1,272,682,0.40,Image,0,0,2019-04-17 15:42:00,2019,4,17,15,42,Wednesday,True
9,1,304,688,0.45,Images,3,0,2019-04-11 15:00:00,2019,4,11,15,0,Thursday,True
10,1,295,689,0.43,Images,4,0,2019-04-10 17:52:00,2019,4,10,17,52,Wednesday,True
11,1,297,693,0.44,Image,0,2,2019-04-06 14:05:00,2019,4,6,14,5,Saturday,False
12,1,336,695,0.49,Images,3,0,2019-04-04 15:06:00,2019,4,4,15,6,Thursday,True
13,1,485,699,0.71,Images,0,4,2019-03-31 19:37:00,2019,3,31,19,37,Sunday,False
14,1,307,701,0.45,Images,4,0,2019-03-29 14:18:00,2019,3,29,14,18,Friday,True
15,1,384,702,0.56,Images,3,3,2019-03-28 20:13:00,2019,3,28,20,13,Thursday,True
16,1,325,702,0.48,Image,4,6,2019-03-28 13:45:00,2019,3,28,13,45,Thursday,True
17,1,264,706,0.39,Image,4,0,2019-03-24 14:44:00,2019,3,24,14,44,Sunday,False
18,1,359,707,0.53,Images,3,0,2019-03-23 18:32:00,2019,3,23,18,32,Saturday,False
19,1,352,710,0.52,Images,4,1,2019-03-20 17:36:00,2019,3,20,17,36,Wednesday,True
20,1,455,713,0.67,Images,3,0,2019-03-17 21:23:00,2019,3,17,21,23,Sunday,False
21,1,335,713,0.49,Image,0,1,2019-03-17 13:38:00,2019,3,17,13,38,Sunday,False
22,1,347,715,0.51,Images,3,0,2019-03-15 16:29:00,2019,3,15,16,29,Friday,True
23,1,357,720,0.53,Images,0,0,2019-03-10 18:24:00,2019,3,10,18,24,Sunday,False
24,1,278,720,0.41,Image,0,1,2019-03-10 13:47:00,2019,3,10,13,47,Sunday,False
25,1,350,720,0.51,Image,0,6,2019-03-10 12:45:00,2019,3,10,12,45,Sunday,False
26,1,324,723,0.48,Images,1,12,2019-03-06 23:04:00,2019,3,6,23,4,Wednesday,True
27,1,289,724,0.42,Image,0,13,2019-03-06 14:11:00,2019,3,6,14,11,Wednesday,True
28,1,299,725,0.44,Images,1,0,2019-03-05 13:50:00,2019,3,5,13,50,Tuesday,True
29,1,323,726,0.47,Images,2,1,2019-03-04 14:00:00,2019,3,4,14,0,Monday,True
30,1,372,727,0.55,Images,2,3,2019-03-03 19:42:00,2019,3,3,19,42,Sunday,False
31,1,316,727,0.46,Image,0,6,2019-03-03 13:58:00,2019,3,3,13,58,Sunday,False
32,1,446,730,0.66,Images,0,3,2019-02-28 14:26:00,2019,2,28,14,26,Thursday,True
33,1,308,730,0.45,Images,0,0,2019-02-28 14:22:00,2019,2,28,14,22,Thursday,True
34,1,306,731,0.45,Images,0,1,2019-02-27 15:00:00,2019,2,27,15,0,Wednesday,True
35,1,355,733,0.52,Images,0,1,2019-02-25 18:03:00,2019,2,25,18,3,Monday,True
36,1,358,734,0.53,Images,0,13,2019-02-24 20:38:00,2019,2,24,20,38,Sunday,False
37,1,327,734,0.48,Image,0,0,2019-02-24 14:13:00,2019,2,24,14,13,Sunday,False
38,1,349,737,0.51,Images,3,0,2019-02-21 14:07:00,2019,2,21,14,7,Thursday,True
39,1,366,741,0.54,Images,0,1,2019-02-17 19:43:00,2019,2,17,19,43,Sunday,False